# Generated by Django 4.2.7 on 2023-12-01 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_order_orderproduct_order_products_order_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('location', models.CharField(max_length=220)),
                ('opening_hours', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='StoreInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_inventory', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_inventory', to='products.store')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='products',
            field=models.ManyToManyField(through='products.StoreInventory', to='products.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='stores',
            field=models.ManyToManyField(through='products.StoreInventory', to='products.store'),
        ),
    ]
