# Generated by Django 4.2.7 on 2023-12-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_store_storeinventory_store_products_product_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='delivery',
            field=models.BooleanField(null=True),
        ),
    ]
