# Generated by Django 4.2.7 on 2023-12-01 18:25

from django.db import migrations, models
import products.models.store_inventory


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_store_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinventory',
            name='county_of_origin',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='storeinventory',
            name='quantity',
            field=models.FloatField(null=True, validators=[products.models.store_inventory.non_negative_validator]),
        ),
    ]
